Repository jellyfin/jellyfin-plugin-ldapauth, pull requests merged in 2021-11, with the labels that each got.

#89 10.8 support
  .github/workflows/build-dotnet.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/command-dispatch.yaml
  .github/workflows/command-rebase.yaml
  .github/workflows/test-dotnet.yml
  .github/workflows/update-release-draft.yml
  LDAP-Auth/LDAP-Auth.csproj
  build.yaml
Labels: chore

#93 Fix #92 - Re-registering of "pageshow" handler
  LDAP-Auth/Config/configPage.html
Labels: bug

#90 Add 'Enable All Folders' or selected folder list for LDAP user create
  LDAP-Auth/Config/PluginConfiguration.cs
  LDAP-Auth/Config/configPage.html
  LDAP-Auth/LDAPAuthenticationProviderPlugin.cs
Labels: feature

#96 Changing the LDAP Admin filter can change existing LDAP authenticating users
  LDAP-Auth/Config/configPage.html
  LDAP-Auth/LDAPAuthenticationProviderPlugin.cs
Labels: feature

#99 Update README build steps to require .Net 6.x
  README.md
Labels: skip-changelog, documentation
